config/routes.rb
Rails.application.routes.draw do
  get "log_out" => "admin_sessions#destroy", :as => "log_out"
  get "sign_up" => "admins#new", :as => "sign_up"
  root :to => "admin_sessions#new"
  resources :admins
  resources :admin_sessions
  get 'dashboard' => 'dashboards#dashboard_4', as: 'dashboard'

  devise_for :user, only: [], stateless_token: true, skip: :sessions

	post 'v2/users/update_last_active', to: 'v2/users#update_last_active'
  get 'get_tasks_users', to: 'tasks#get_users'

  resources :users do 
    member do
      post :deactivate
      post :reactivate
    end
  end
  resources :tasks
  resources :categories
  resources :quickblox
  namespace :v2, defaults: { format: :json } do
    resource :login, only: [:create], controller: :sessions
    resources :users, only: [:index, :create, :update, :show, :destroy] do
      collection do
        get :filter, :get_user_id, :posted_tasks
        post :verify_phone
        post :check_nudity
        get 'identification_validation/all' => 'users#list_id_validation'
      end
      member do
        post :update_role
        delete :force_logout
        get :worked_tasks, :task_bids, :picture, :task_counts, :activity
      end
      resources :tasks, only: [:index]
      resource :rating, only: [:create], controller: :ratings
      resources :reviews, only: [:index] do
        collection do
          post :check_new_reviews
          get  :rating_count
        end
      end
      resources :skills
      resources :portfolio_images, only: [:index, :create, :show, :destroy]
      post 'avatar' => 'avatars#upload'
      post 'identification_validation/ban' => 'users#ban_id_validation'
      post 'identification_validation/clear' => 'users#clear_id_validation'
    end

    namespace :chats do
    	get :get_token
    end

    resources :passwords do
      member do
        put :admin_update
        put :reset_password
      end
    end
    resources :tasks do
      collection do
        get  :task_images
        get  :statuses
        post :search
        post :check_new_tasks
        get  :assigned_tasks
        post :list_task_dates
        get  :users_tasks
        get  :open_tasks
      end
      member do
        post :archive
        post :create_group_chat
        get  :get_image
        get  :get_category
      end
      resources :offers, only: [:index, :create], controller: :task_work_offers do
        post 'take'   => 'task_work_offers#take_offer'
        post  'accept' => 'task_work_offers#accept_offer'
        post  'unassign' => 'task_work_offers#unassign_offer'
        post 'pay'    => 'task_work_offers#pay_worker'
        post 'complete'   => 'task_work_offers#work_complete'
        post 'temp_complete'   => 'task_work_offers#temp_work_complete'
        post 'cancel'   => 'task_work_offers#cancel_offer'
        collection do
          get :tasker_offers
        end
      end
      resource :review, only: [:create], controller: :reviews
      resources :comments
      resources :images
    end
    resources :payments, only: [:create] do
      collection do
        post :charge_client
        post :ipn_notify
        get  :get_client_token
        post :sub_merchant
        post :update_sub_merchant
        get  :sub_merchant_info
        post :webhook_notification
      end
    end
    resources :devices
    resources :feedbacks, only: [:index, :create, :show]
    resources :categories, only: [:index, :create, :update, :show, :destroy] do
      resources :category_images, only: [:index, :create, :update, :show, :destroy]
    end
    resources :feedback_categories, only: [:index, :create, :update, :show, :destroy]

    # sockets_for :conversations do
    #   sockets_for :messages
    # end

    resources :contacts, only: [:create]

    resources :faqs, only: [:index, :create, :update]
    put 'user_notifications/mark_read', to: 'user_notifications#mark_read'
    put 'user_notifications/mark_delete', to: 'user_notifications#mark_delete'
    get 'user_notifications/get_all', to: 'user_notifications#get_all'
    put 'users/:id/activity', to: 'users#mark_activity_read'
    get 'users/:id/unread_activity_count', to: 'users#unread_activities'

    resources :user_notifications, only: [:index, :create, :show]
  end

  post 'v2/auth/facebook/callback', to: 'v2/sessions#facebook_login'
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  skip_before_filter :verify_authenticity_token
  before_filter :get_task, only: [:show,:edit,:destroy]
  before_filter :authenticate_admin!

  def protect_against_forgery?
    false
  end

  def index
    if params[:id].present? || params[:status].present? || params[:category_id].present?
      @tasks = Task.filter(params.slice(:id, :status, :category_id)).page params[:page]
      @tasks_filter_params = params.slice(:id, :status, :category_id)
    else
      @tasks = Task.all
    end
    @tasks = Task.filter_by_poster(params[:poster],@tasks) if params[:poster].present?
    if params[:price_range].present?
      @min_price, @max_price = params[:price_range].split(/;/)
      @tasks = Task.filter_by_price_range(@min_price, @max_price,@tasks)
    end
    if params[:date_range].present?
      @start_date,@end_date = params[:date_range].split("-")
      @tasks = Task.filter_by_date_range(@start_date,@end_date,@tasks) 
    end
    @tasks = @tasks.order("#{sort_column_for_tasks} #{sort_direction}").page params[:page]
  end

  def get_users
    email_list = User.all.select(:id, :email).map{|u| {name: u.email, code: u.id}}
    # first_name_list = User.all.select(:id, :first_name).where.not(first_name: nil).where.not(first_name: "").
                      # map{|u| {name: u.first_name,code: u.id}}
    render json: (email_list), root: false
  end

  def show
    if @task
      @task_image = CategoryImage.find_by(id: @task.category_id).present? ? CategoryImage.find_by(id: @task.category_id).link : @task.imageLinks.first
    end
  end
 
  def edit
  end

  def create
  end

  def new
  end

  def destroy
    if @task.destroy
      redirect_to tasks_path
    end
  end

  def update
  end

private

  def get_task
    @task = Task.find_by(id: params[:id])
  end

end

app/controllers/v2/tasks_controller.rb
module V2

  class TasksController < ApplicationController
    include UploadToCloud

    skip_before_action :authenticate_user_from_token!, only: [:check_new_tasks]
    before_action :find_task, only: [:update, :destroy, :archive, :create_group_chat, :complete, :get_image, :get_category]

    # GET /v1/tasks
    # Get all the tasks
    def index
      per_page = params[:per_page].blank? ? 20 : params[:per_page].to_i

      @user = current_user

      if params[:per_page] == 'all'
        @tasks = policy_scope(Task).all
      else
        @tasks = policy_scope(Task).all.page(params[:page]).per(per_page)
      end
      @tasks =  @tasks.status(params[:status]).page(params[:page]).per(per_page) if params[:status].present?
      @tasks = @tasks.category(params[:category].downcase.gsub(/\s+/, "")).page(params[:page]).per(per_page) if params[:category].present?
      @tasks = Task.where(user_id: params[:user_id]).desc.page(params[:page]).per(per_page) if params[:user_id]
      @tasks = Task.find_by_fuzzy_name(params[:search]).page(params[:page]).per(per_page) if params[:search].present?
      @tasks = Task.by_date(params[:date]).desc.page(params[:page]).per(per_page) if params[:date].present?
    end

    def show
      @task = policy_scope(Task).find(params[:id])
      @user = current_user

      offers_list = []
      @offers_arr = @task.work_offers

      @offers_by_worker = @offers_arr.group_by { |o| o.worker_id }
      
      @offers_by_worker.each do |worker, offers|
        offers_list << offers.last
      end
      @offers = offers_list.sort { |a,b| a.created_at <=> b.created_at }
    end

    # POST /v1/tasks
    # Add a new task
    def create
      # Create a new task with following params except imageLinks. Or else the
      # task will have base64 image as attribute.
      authorize Task
      @user = current_user
      
      @task = Task.new(task_params.except(:images_attributes))
      if @task.save
        
        unless task_params[:images_attributes].blank?
          task_params[:images_attributes].each do |img|
            image_hash = {}
            link = task_image_upload(@task.id, img[1][:link])
            
            image_hash[:link] = link
            image_hash[:width] = img[1][:width]
            image_hash[:height] = img[1][:height]
            @task.images.create(image_hash)
          end
        end

        render :action => "show"
      else
        render json: { status: { error: @task.errors.full_messages }}, status: :unprocessable_entity
      end
    end

    def update
      authorize @task

      @user = current_user
      if update_params[:images_attributes]
        update_params[:images_attributes].each do |img|
            image_hash = {}
            link = task_image_upload(@task.id, img[1][:link]) unless img[1][:link].blank?
            
            image_hash[:link] = link unless img[1][:link].blank?
            image_hash[:width] = img[1][:width] unless img[1][:width].blank?
            image_hash[:height] = img[1][:height] unless img[1][:height].blank?

            @task_image = nil          
            @task_image = @task.images.find img[1][:id].to_i rescue nil

            if  @task_image.blank?
              @task.images.create(image_hash)
            else
              unless img[1][:delete].blank?
                @task_image.destroy
              else
                @task_image.update_attributes(image_hash)
              end
            end
          end
      else
        puts "No imageLinks"
      end
      render_errors(@task) unless @task.update(update_params.except(:images_attributes))
      render :action => "show"
    end

    def destroy
      authorize @task
      @task.destroy
      head :no_content
    end

    def statuses
      arr = []
      @statuses = Task.statuses.each {|key, value| arr.push({label: key, value: value})}
    end

    def task_images
      @tasks = policy_scope(Task).all
    end

    def search
      @user = current_user
      if params[:users].blank? && params[:q].blank?
        render json: { status: { error: ["Invalid search parameter."] }}, status: :unprocessable_entity
        return
      end

      per_page = params[:per_page].blank? ? 20 : params[:per_page].to_i

      if params[:users].blank? && !params[:q].blank?
        # Common search
        @search = Task.ransack(params[:q])
      else
        # Distance search
        if !params[:users].blank? && (!params[:users][:latitude].blank? && !params[:users][:longitude].blank?)
          order_by = params[:order].blank? ? "distance asc" : params[:order]          
          @search = Task.near([params[:users][:latitude], params[:users][:longitude]], params[:miles]).reorder(order_by)

          @search = @search.ransack(params[:q]) unless params[:q].blank?

          @user.update_attributes(latitude: params[:users][:latitude], longitude: params[:users][:longitude])
        end
      end

      # Sort the search result
      @search.sorts = params[:sort] unless params[:sort].blank? || params[:q].blank?

      unless params[:q].blank?

        unless params[:q][:category_id_cont_any].blank?
          # Category search
          all_category_ids = Category.where(id: params[:q][:category_id_cont_any])
          @category_tasks = @search.result.where(:category_id => all_category_ids)
          category_result = true
        end

        @tasks = category_result ? @category_tasks : @search.result.page(params[:page]).per(per_page)
      else
        @tasks = @search.page(params[:page]).per(per_page)
      end
    end

    def archive
      authorize @task

      @task.update_attributes(archived: true)
      head :no_content
    end

    ## API to check new task is there or not with "aftertime" parameter
    def check_new_tasks
      if params[:after_time].blank?
        render json: { status: { error: ["DateTime can't be blank."] }}, status: :unprocessable_entity
        return
      end

      parsed_time = DateTime.strptime(params[:after_time], '%d/%m/%Y %H:%M:%S')
      @task_count = Task.where("created_at > ?", parsed_time.to_s).count
      response_text = @task_count > 0 ? "Yes" : "No"

      render json: { result: response_text }
    end

    def create_group_chat
      if group_chat_params[:group_chat_id]
        @task.update_attribute(:group_chat_id, group_chat_params[:group_chat_id])
        render :action => "show"
      else
        render json: { status: { error: "Missing group chat ID" }}, status: :unprocessable_entity
      end
    end

    def assigned_tasks
      @user = current_user
      authorize @user

      per_page = params[:per_page].blank? ? 20 : params[:per_page].to_i

      @assigned_tasks = @user.assigned
      @tasks = @assigned_tasks.page(params[:page]).per(per_page)

      render :action => "index"
    end

    ## Give list of dates whiich has tasks to show orange color in calender
    def list_task_dates
      @user = current_user
      authorize Task

      dates_array = []
      @tasks = []
      dt = DateTime.new(params[:year].to_i, params[:month].to_i, 1)
      start_date = dt.to_date.beginning_of_month
      end_date = dt.to_date.end_of_month

      @tasks = @user.tasks.by_month_and_year(params[:month], params[:year])

      ## Tasks which current user is posted any bid
      offer_task_ids = @user.task_work_offers.pluck(:task_id).uniq
      posted_offer_tasks = Task.where(id: offer_task_ids, created_at: start_date..end_date).order(created_at: :desc)

      ## Tasks which is assigned to current user
      offer_task_ids = @user.task_work_offers.where.not(task_date: nil).pluck(:task_id).uniq
      assigned_tasks = Task.where(id: offer_task_ids, created_at: start_date..end_date).order(created_at: :desc)

      posted_offer_tasks.map {|p| @tasks << p } unless posted_offer_tasks.first.nil?
      assigned_tasks.map {|a| @tasks << a } unless assigned_tasks.first.nil?

      dates_array = @tasks.group_by { |t| t.created_at.strftime("%Y-%m-%d") }.map(&:first)

      render json: { task_dates: dates_array }
    end

    def complete
      authorize @task
      
      @task.completed!
      @task_work_offers = @task.work_offers.where(status: TaskWorkOffer.statuses[:approved])
      
      @task_work_offers.each do |offer|
        offer.completed!
      end
      
      render json: { status:{ success: "Task has been completed."} }
    end

    def get_image
      unless @task.blank?
        if @task.images.blank?
          @task_image = @task.category.category_images.enabled.first.link rescue nil
        else
          @task_image = @task.images.first.link rescue nil
        end
        
        @task_image.blank? ? (render :plain => "No image found") : (redirect_to @task_image)
      else
        render json: { status: { error: ["Couldn't find task."] }}, status: :unprocessable_entity
      end
    end

    def get_category
      unless @task.blank?

        task_category = @task.category
        @category = task_category ? @task.category.name : "Nil"

        render :plain => @category
      else
        render json: { status: { error: ["Couldn't find task."] }}, status: :unprocessable_entity
      end
    end

    def users_tasks
      @user = current_user
      authorize @user

      per_page = params[:per_page].blank? ? 20 : params[:per_page].to_i

      @tasks = []
      start_date = params[:date].to_date.beginning_of_day
      end_date = params[:date].to_date.end_of_day

      if params[:date].present?
        @tasks << @user.tasks.by_date(params[:date]).desc

        ## Tasks which current user is posted any bid
        offer_task_ids = @user.task_work_offers.pluck(:task_id).uniq
        posted_offer_tasks = Task.where(id: offer_task_ids, created_at: start_date..end_date).order(created_at: :desc)

        ## Tasks which is assigned to current user
        offer_task_ids = @user.task_work_offers.where.not(task_date: nil).pluck(:task_id).uniq

app/helpers/tasks_helper.rb
module TasksHelper
  include ApplicationHelper

  def filter_status_selector
    @tasks_filter_params.present? ? @tasks_filter_params[:status] : nil
  end

  def filter_category_selector
    @tasks_filter_params.present? ? @tasks_filter_params[:category_id].to_i : nil
  end

  def date_range_value_maker
  	(@start_date && @end_date) ? "#{@start_date} - #{@end_date}" : ""
  end

  def task_images
  	images = @task.images.pluck(:link)
  	if !images.present? && CategoryImage.find_by(id: @task.category_id).present?
  		images = [CategoryImage.find_by(id: @task.category_id).link]
  	end
  	images
  end

end

app/views/tasks/_task_filter_form.html.erb
<%= form_tag(tasks_path, :method => :get) do %>
    <div class="ibox-content m-b-sm border-bottom">
      <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <label class="control-label" for="task_id">Task ID</label>
            <%= text_field_tag(:id,params[:id], :class => 'form-control',:placeholder => "ID") %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <label class="control-label" for="status">Task status</label>
            <%#= text_field_tag(:status,params[:status], :class => 'form-control',:placeholder => "Status") %>
            <%= select_tag 'status', options_for_select([["Select",""],["Open", 0], ["Saved", 1], ["In Progress", 2], ["Completed", 3]], :selected => filter_status_selector),:class=> 'form-control m-b' %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <label class="control-label" for="poster">Poster</label>
            <%= text_field_tag(:poster,params[:poster], :class => 'form-control',:placeholder => "Enter Email", id: "search-poster") %>

          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <div class="form-group">
            <label class="control-label" for="date_added" style="margin-bottom: 20px;">Date Range</label>
            <div class="input-group date">
              <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
              <%= text_field_tag(:date_range,params[:date_range], :class => 'form-control',:value=> date_range_value_maker, name: "date_range") %>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <label class="control-label" for="task-name" style="margin-bottom: 20px;" >Category</label>
            <%#= text_field_tag(:category,params[:category], :class => 'form-control', :placeholder => "Category") %>
            <%= select_tag('category_id', options_for_select([["Select",""]] + Category.all.collect {|c| [c.name.titleize, c.id]},{ include_blank: true,:selected =>  filter_category_selector}), :class=> 'form-control m-b') %>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="form-group">
            <label class="control-label" for="amount">Price Range</label>
              <%= text_field_tag(:price_range,params[:price_range], :id => 'range',:value=>"") %>
          </div>
        </div>
        <div class="col-sm-4"></div>
        <div class="col-sm-4" style="padding-top: 15px">
            <div class="form-group">
              <%= submit_tag "Submit",class: "btn btn-sm btn-primary bold","style" => "font-size: 14px" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/tasks/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#">Config option 1</a>
                        </li>
                        <li><a href="#">Config option 2</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
            <%= form_for(@task,:html => {:class => 'form-horizontal'}) do |f| %>
              <div class="form-group"><label class="col-sm-2 control-label">Description</label>
                <div class="col-sm-10">
                  <%= f.text_area :description, class: "form-control" %>
                </div>
              </div>
              <div class="hr-line-dashed"></div>

              <div class="form-group"><label class="col-sm-2 control-label">Price</label>
                <div class="col-sm-10">
                  <%= f.text_field :price, class: "form-control" %>
                </div>
              </div>

              <div class="form-group"><label class="col-sm-2 control-label">Description</label>
                <div class="col-sm-10">
                  <%= f.text_area :description, class: "form-control" %>
                </div>
              </div>
              <div class="hr-line-dashed"></div>

              
              <div class="hr-line-dashed"></div>
              <div class="form-group">
                <div class="col-sm-4 col-sm-offset-2">
                  <%= f.submit class: "btn btn-primary" %>
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>  
</div>

<% content_for :javascript do %>

  <script type="text/javascript">

  $(function() {

      $('.i-checks').iCheck({
          checkboxClass: 'icheckbox_square-green',
          radioClass: 'iradio_square-green',
      });

  });

  </script>

<% end %>

app/views/tasks/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Tasks</h2>
  </div>
  <div class="col-lg-2">
  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight ecommerce">
  <%= render 'task_filter_form' %>

  <div class="row">
      <div class="col-lg-12">
          <div class="ibox">
              <div class="ibox-content">
                <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
                  <thead>
                    <tr>
                      <th><%= sort_link "id", "Task ID" %></th>
                      <th data-hide="phone">Task</th>
                      <th><%= sort_link "price" %></th>
                      <th><%= sort_link "created_at", "Posted On" %></th>
                      <th data-hide="phone,tablet" >Posted By</th>
                      <th data-hide="phone">Status</th>
                      <th class="text-right" colspan="2">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @tasks.each do |task| %>
                      <tr>
                        <td><%= task.id %></td>
                        <td><%= link_to(truncate(task.description,:length => 47), task_path(task)) %></td>
                        <td><%= task.price %></td>
                        <td><%= task.created_at.to_date %></td>
                        <td><%= link_to (task.user.full_name || task.user.email), user_path(task.user_id) %></td>
                        <td>
                          <% if task.status == "completed" %>
                            <span class="label label-primary">Completed</span>
                          <% elsif task.status == "in_progress" %>
                            <span class="label label-info">In Progress</span>
                          <% elsif task.status == "saved" %>
                            <span class="label label-success">Saved</span>
                          <% else %>
                            <span class="label label-warning">Open</span>
                          <% end %>
                        </td>
                        <td class="text-right" colspan="2">
                          <div class="btn-group">
                            <!-- <button class="btn-white btn btn-xs"><%= link_to("View", task_path(task)) %></button> -->
                            <button class="btn-white btn btn-xs"><%= link_to("Edit", edit_task_path(task)) %></button>
                            <button class="btn-white btn btn-xs"><%= link_to("Delete", task_path(task), method: :delete,  :data => {:confirm => 'Are you sure You would like to delete this Task?'}) %></button>
                          </div>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                  <tfoot>
                    <tr>
                      <td colspan="7">
                        <ul class="pagination pull-right"><%= paginate @tasks %></ul>
                      </td>
                    </tr>
                  </tfoot>
                </table>
              </div>
          </div>
      </div>
  </div>
</div>
<% content_for :javascript do %>
  <script type="text/javascript">
    // $(function() {
    //   $('.footable').footable();
    // });
    $(function () {
        $("#range").ionRangeSlider({         //Range slider implemented from http://ionden.com/a/plugins/ion.rangeSlider/en.html
            hide_min_max: true,
            keyboard: true,
            min: 0,
            max: 5000,
            from: '<%= @min_price || 0 %>',
            to: '<%= @max_price || 2000 %>',
            type: 'double',
            step: 1,
            prefix: "$",
            grid: true
        });

    });
  </script>
  <script type="text/javascript">
    var options = {
      url: "/get_tasks_users",

  getValue: "name",

  list: { 
    match: {
      enabled: true
    }
  },

  theme: "square"
};

$("#search-poster").easyAutocomplete(options);
  </script>

<script type="text/javascript">
$(function() {

  $('input[name="date_range"]').daterangepicker({
      autoUpdateInput: false,
      locale: {
          cancelLabel: 'Clear'
      }
  });

  $('input[name="date_range"]').on('apply.daterangepicker', function(ev, picker) {
      $(this).val(picker.startDate.format('MM/DD/YYYY') + ' - ' + picker.endDate.format('MM/DD/YYYY'));
  });

  $('input[name="date_range"]').on('cancel.daterangepicker', function(ev, picker) {
      $(this).val('');
  });

});
</script>

<% end %>

app/views/tasks/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Task detail</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to "Home", dashboard_path %>
      </li>
      <li>
        <%= link_to "Tasks", tasks_path %>
      </li>
      <li class="active">
        <strong>Task Detail</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">

<div class="row">
  <div class="col-lg-12">

    <div class="ibox product-detail">
      <div class="ibox-content">
        <div class="row">
          <div class="col-md-5">

             <div class="product-images">
                <% task_images.each do |image| %>
                  <div>
                    <div class="image-imitation" style="padding: 0px;">
                      <%= image_tag(image, height: '320', width: '335')%>
                    </div>
                  </div>
                <% end %>
              </div>

          </div>
          <div class="col-md-7">
              <h2 class="font-bold m-b-xs">
                  <%= @task.description %>
              </h2>
              <small>Posted by: <%= @task.user.full_name %></small>
              <div class="m-t-md">
                  <h2 class="product-main-price">$<%= @task.price %></h2>
              </div>
              <hr>
              <h4>Product description</h4>
              <div class="small text-muted">
                  It is a long established fact that a reader will be distracted by the readable
                  content of a page when looking at its layout. The point of using Lorem Ipsum is

                  <br/>
                  <br/>
                  There are many variations of passages of Lorem Ipsum available, but the majority
                  have suffered alteration in some form, by injected humour, or randomised words
                  which don't look even slightly believable.
              </div>
              <dl class="small m-t-md">
                  <dt>Description lists</dt>
                  <dd>A description list is perfect for defining terms.</dd>
                  <dt>Euismod</dt>
                  <dd>Vestibulum id ligula porta felis euismod semper eget lacinia odio sem nec elit.</dd>
                  <dd>Donec id elit non mi porta gravida at eget metus.</dd>
                  <dt>Malesuada porta</dt>
                  <dd>Etiam porta sem malesuada magna mollis euismod.</dd>
              </dl>
              <hr>

              <div>
                  <div class="btn-group">
                      <button class="btn btn-primary btn-sm"><i class="fa fa-cart-plus"></i> Add to cart</button>
                      <button class="btn btn-white btn-sm"><i class="fa fa-star"></i> Add to wishlist </button>
                      <button class="btn btn-white btn-sm"><i class="fa fa-envelope"></i> Contact with author </button>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<% content_for :javascript do %>

<script type="text/javascript">


$(window).load(function() {

    $('.product-images').slick({
        dots: true
    });

});

</script>

<% end %>