config/routes.rb
Rails.application.routes.draw do
  get "log_out" => "admin_sessions#destroy", :as => "log_out"
  get "sign_up" => "admins#new", :as => "sign_up"
  root :to => "admin_sessions#new"
  resources :admins
  resources :admin_sessions
  get 'dashboard' => 'dashboards#dashboard_4', as: 'dashboard'

  devise_for :user, only: [], stateless_token: true, skip: :sessions

	post 'v2/users/update_last_active', to: 'v2/users#update_last_active'
  get 'get_tasks_users', to: 'tasks#get_users'

  resources :users do 
    member do
      post :deactivate
      post :reactivate
    end
  end
  resources :tasks
  resources :categories
  resources :quickblox
  namespace :v2, defaults: { format: :json } do
    resource :login, only: [:create], controller: :sessions
    resources :users, only: [:index, :create, :update, :show, :destroy] do
      collection do
        get :filter, :get_user_id, :posted_tasks
        post :verify_phone
        post :check_nudity
        get 'identification_validation/all' => 'users#list_id_validation'
      end
      member do
        post :update_role
        delete :force_logout
        get :worked_tasks, :task_bids, :picture, :task_counts, :activity
      end
      resources :tasks, only: [:index]
      resource :rating, only: [:create], controller: :ratings
      resources :reviews, only: [:index] do
        collection do
          post :check_new_reviews
          get  :rating_count
        end
      end
      resources :skills
      resources :portfolio_images, only: [:index, :create, :show, :destroy]
      post 'avatar' => 'avatars#upload'
      post 'identification_validation/ban' => 'users#ban_id_validation'
      post 'identification_validation/clear' => 'users#clear_id_validation'
    end

    namespace :chats do
    	get :get_token
    end

    resources :passwords do
      member do
        put :admin_update
        put :reset_password
      end
    end
    resources :tasks do
      collection do
        get  :task_images
        get  :statuses
        post :search
        post :check_new_tasks
        get  :assigned_tasks
        post :list_task_dates
        get  :users_tasks
        get  :open_tasks
      end
      member do
        post :archive
        post :create_group_chat
        get  :get_image
        get  :get_category
      end
      resources :offers, only: [:index, :create], controller: :task_work_offers do
        post 'take'   => 'task_work_offers#take_offer'
        post  'accept' => 'task_work_offers#accept_offer'
        post  'unassign' => 'task_work_offers#unassign_offer'
        post 'pay'    => 'task_work_offers#pay_worker'
        post 'complete'   => 'task_work_offers#work_complete'
        post 'temp_complete'   => 'task_work_offers#temp_work_complete'
        post 'cancel'   => 'task_work_offers#cancel_offer'
        collection do
          get :tasker_offers
        end
      end
      resource :review, only: [:create], controller: :reviews
      resources :comments
      resources :images
    end
    resources :payments, only: [:create] do
      collection do
        post :charge_client
        post :ipn_notify
        get  :get_client_token
        post :sub_merchant
        post :update_sub_merchant
        get  :sub_merchant_info
        post :webhook_notification
      end
    end
    resources :devices
    resources :feedbacks, only: [:index, :create, :show]
    resources :categories, only: [:index, :create, :update, :show, :destroy] do
      resources :category_images, only: [:index, :create, :update, :show, :destroy]
    end
    resources :feedback_categories, only: [:index, :create, :update, :show, :destroy]

    # sockets_for :conversations do
    #   sockets_for :messages
    # end

    resources :contacts, only: [:create]

    resources :faqs, only: [:index, :create, :update]
    put 'user_notifications/mark_read', to: 'user_notifications#mark_read'
    put 'user_notifications/mark_delete', to: 'user_notifications#mark_delete'
    get 'user_notifications/get_all', to: 'user_notifications#get_all'
    put 'users/:id/activity', to: 'users#mark_activity_read'
    get 'users/:id/unread_activity_count', to: 'users#unread_activities'

    resources :user_notifications, only: [:index, :create, :show]
  end

  post 'v2/auth/facebook/callback', to: 'v2/sessions#facebook_login'
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :verify_authenticity_token
  before_filter :authenticate_admin!
  before_filter :get_user, only: [:show,:edit,:update,:destroy,:deactivate, :reactivate]

  def protect_against_forgery?
    false
  end

  def index
    if params["name_or_email"].present?
      filter = FilterPresenter.new
      @users = filter.get_users(params["name_or_email"])
      @users = @users.order("#{sort_column_for_users} #{sort_direction}").page params[:page]
      # @users = @stats.all_users(params[:search]).order("created_at desc")
    else
      @users = User.order("#{sort_column_for_users} #{sort_direction}").page params[:page]
    end
  end

  def show
  end
 
  def edit
  end

  def create
  end

  def new
  end

  def destroy
    if @user.destroy
      redirect_to users_path
    else
      render :show
    end
  end

  def deactivate
    @user.deactivate_user
    redirect_to user_path @user
  end

  def reactivate
    @user.reactivate_user
    redirect_to user_path @user
  end

  def update
    if @user.update(user_params)
      # flash[:notice] = 'Marketing Message was successfully updated.'
      redirect_to users_path
    else
      # flash.now[:error] = "Marketing message could not be updated."
      render :show
    end
  end

private

  def get_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email,:first_name,:last_name,:description,:phone_number,:username,:rating,:role)
  end

end

app/controllers/v2/users_controller.rb
module V2
  class UsersController < ApplicationController
    skip_before_action :authenticate_user_from_token!, only: [:create, :filter, :verify_phone]
    before_filter :find_user, only: [:show, :destroy, :update_role, :force_logout, :worked_tasks, 
                  :ban_id_validation, :clear_id_validation, :task_bids, :picture, :task_counts, :activity]

    include PhoneValidate

    def index
			authorize User
    	@users = User.all
    end

    # POST /v1/users
    # Creates an user
    def create
      @user = User.new user_params
      @quickblox_user = QuickbloxUser.new(@user)

      if @quickblox_user.create
        render json: @user, serializer: V2::SessionSerializer, root: nil
      else
        render json: { status: { error: @user.errors.full_messages }}, status: :unprocessable_entity
      end
    end

    # PUT /v2/users
    # Updates an user
    def update
      @user = current_user
      authorize @user

      if @user.update(update_params)
        render :action => "show"
      else
        render json: { status: { error: @user.errors.full_messages }}, status: :unprocessable_entity
      end
    end

    def filter
      if params[:username]
        @user = User.find_by_username(params[:username])
      elsif params[:email]
        @user = User.find_by_email(params[:email])
      else
        render json: { status: { error: ["Couldn't find user."] }}, status: :unprocessable_entity
        return
      end
    end

    def update_role
      authorize current_user

      if @user.update_attributes(role: params[:user][:role])
        render json: { status: { success: "User role has been changed successfully." }}
      else
        render json: { status: { error: @user.errors.full_messages }}, status: :unprocessable_entity
      end
    end

    def force_logout
      authorize current_user
      sign_out @user
      head :no_content
    end

    def worked_tasks
      authorize current_user

      per_page = params[:per_page].blank? ? 20 : params[:per_page].to_i

      if @user
        @tasks = @user.worked.page(params[:page]).per(per_page)
      else
        render json: { status: { error: ["Couldn't find user."] }}, status: :unprocessable_entity
        return
      end
    end

    def update_last_active
    	authorize current_user
      @user = current_user
      @user.update_attributes(last_active: Time.now)
      head :no_content
      return
    end

    def verify_phone
      unless params[:user][:phone_number].blank?
        result = verify(params[:user][:phone_number])
        if result
          render json: result
        else
          render json: { status: { error: ["Unknown error. Please try again or contact support."] }}, status: :unprocessable_entity
          return
        end
      else
        render json: { status: { error: ["Phone number can't be blank."] }}, status: :unprocessable_entity
        return
      end
    end

    def activity
      per_page = params[:per_page].blank? ? 20 : params[:per_page].to_i
      @activities = PublicActivity::Activity.order("created_at desc").where(recipient_id: current_user, recipient_type: "User").page(params[:page]).per(per_page)
    end

    def mark_activity_read
      user_activities = PublicActivity::Activity.where(recipient_id: current_user.id)
      user_activities.each do |activity|
        activity.read_status = true
        activity.save
      end
      render :json => {:success => true}
    end

    def unread_activities
      user_activities = PublicActivity::Activity.where(recipient_id: current_user.id).where(read_status: nil)
      @count = user_activities.count
      render :json => {:unread_count => @count}
    end

    def check_nudity
      authorize current_user
      
      if params[:image_url].blank?
        render json: { status: { error: ["Image can't be blank"] }}, status: :unprocessable_entity
      else
        response = Unirest.post "https://api.sightengine.com/1.0/nudity.json", parameters:{
          url: params[:image_url]}, 
          auth:{:api_user=>"#{Rails.application.secrets.sightengine_api_user}", 
                :api_secret=>"#{Rails.application.secrets.sightengine_api_secret}"}

        render json: response.body
      end
    end

    def list_id_validation
      authorize current_user

      per_page = params[:per_page].blank? ? 20 : params[:per_page].to_i
      @users = User.where(verified: false).page(params[:page]).per(per_page)
    end

    def ban_id_validation
      authorize current_user

      @user.update(verified: false)
      render :show
    end

    def clear_id_validation
      authorize current_user

      @user.update(verified: true)
      render :show
    end

    def task_bids
      authorize current_user

      if @user == current_user
        per_page = params[:per_page].blank? ? 20 : params[:per_page].to_i
        @offers = TaskWorkOffer.where(worker_id: @user.id).desc.page(params[:page]).per(per_page)
      else
        render json: { status: { error: ["Couldn't find user."] }}, status: :unprocessable_entity
        return
      end
    end

    def picture
      unless @user.blank?
        if @user.avatar.blank?
          redirect_to 'https://storage.googleapis.com/snaptask_images/user_avatars/default_user.jpg'
        else
          redirect_to @user.avatar
        end
      else
        render json: { status: { error: ["Couldn't find user."] }}, status: :unprocessable_entity
      end
    end

    ## Get user id by facebook uid
    def get_user_id
      @user = User.find_by_uid params[:uid] rescue nil

      if @user
        render json: { user_id: @user.id }
      else
        render json: { status: { error: ["Couldn't find a user."] }}, status: :unprocessable_entity
      end
    end

    def destroy
      authorize current_user

      @user.destroy unless @user == current_user
      head :no_content
    end

    ## Count of Open for offers, Assigned, Awaiting Payments, Completed tasks, My Profile Rating
    def task_counts
      authorize @user

      offer_task_ids = @user.task_work_offers.where(status: TaskWorkOffer.statuses[:completed]).pluck(:task_id)
      completed_tasks_count = Task.where(id: offer_task_ids, status: Task.statuses[:completed]).count

      counts = { open_for_offers: @user.open_for_offers.count, assigned: @user.assigned.count, completed: completed_tasks_count, awaiting_payments: 0, profile_rating: 0 }

      render json: { task_counts: counts }
    end

    ## Tasks for which offers received
    def posted_tasks
      @user = current_user
      authorize @user

      per_page = params[:per_page].blank? ? 20 : params[:per_page].to_i
      @tasks = @user.my_posted_tasks.page(params[:page]).per(per_page)
    end

    private

    def user_params
      params.require(:user).permit(:email, :username, :password, :password_confirmation, :role, :first_name, :last_name)
    end

    def update_params
      params.require(:user).permit(:email, :username, :phone_number, :zipcode, :city, :state, :country, :notify_message_replies, :notify_comment_replies, :notify_task_status, :notify_task_bids, :notify_task_assigned, :push_notify_allowed, :first_name, :last_name, :tag_line, :description, :birthday, :paypal_email_address)
    end

    def find_user
      @user = User.find(params[:id] || params[:user_id]) rescue nil
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  include ApplicationHelper

end

app/views/users/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#">Config option 1</a>
                        </li>
                        <li><a href="#">Config option 2</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
            <%= form_for(@user,:html => {:class => 'form-horizontal'}) do |f| %>
              <div class="form-group"><label class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                  <%= f.text_field :email, class: "form-control" %>
                </div>
              </div>
              <div class="hr-line-dashed"></div>

              <div class="form-group"><label class="col-sm-2 control-label">First Name</label>
                <div class="col-sm-10">
                  <%= f.text_field :first_name, class: "form-control" %>
                </div>
              </div>
              <div class="hr-line-dashed"></div>

              <div class="form-group"><label class="col-sm-2 control-label">Last Name</label>
                <div class="col-sm-10">
                  <%= f.text_field :last_name, class: "form-control" %>
                </div>
              </div>
              <div class="hr-line-dashed"></div>

              <div class="form-group"><label class="col-sm-2 control-label">Description</label>
                <div class="col-sm-10">
                  <%= f.text_area :description, class: "form-control" %>
                </div>
              </div>
              <div class="hr-line-dashed"></div>

              <div class="form-group"><label class="col-sm-2 control-label">Phone Number</label>
                <div class="col-sm-10">
                  <%= f.text_field :phone_number, class: "form-control" %>
                </div>
              </div>
              <div class="hr-line-dashed"></div>

              <div class="form-group"><label class="col-sm-2 control-label">UserName</label>
                <div class="col-sm-10">
                  <%= f.text_field :username, class: "form-control" %>
                </div>
              </div>
              <div class="hr-line-dashed"></div>

              <div class="form-group"><label class="col-sm-2 control-label">Rating</label>
                <div class="col-sm-10">
                  <%= f.text_field :rating, class: "form-control" %>
                </div>
              </div>
              <div class="hr-line-dashed"></div>
              <div class="form-group"><label class="col-sm-2 control-label">Role</label>
                <div class="col-sm-10">
                  <%= f.text_field :role, class: "form-control" %>
                </div>
              </div>
              <div class="hr-line-dashed"></div>
              <div class="form-group">
                <div class="col-sm-4 col-sm-offset-2">
                  <%= f.submit class: "btn btn-primary" %>
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>  
</div>

<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    $('.i-checks').iCheck({
        checkboxClass: 'icheckbox_square-green',
        radioClass: 'iradio_square-green',
    });

});

</script>

<% end %>

app/views/users/index.html.erb
<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
    <div class="input-group">
      <%= form_tag(users_path, :method => :get) do %>
        <%= text_field_tag :name_or_email, params[:name_or_email], placeholder: "Name or Email", class: 'input-sm form-control',style: 'width:80%' %>
        <span class="input-group-btn">
          <%= submit_tag "Go!",class: "btn btn-sm btn-primary" %>
        </span>
      <% end %>
    </div>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
        <tr>
          <th>#</th>
          <th><%= sort_link "email",nil,"user" %></th>
          <th><%= sort_link "first_name", "Username", "user" %></th>
          <th><%= sort_link "created_at", "Joined on", "user" %></th>
          <th><%= sort_link "last_active", nil, "user" %></th>
          <th>Status</th>
          <th>Action</th>
        </tr>
        </thead>
        <tbody>
           <% if @users.present? %>
              <% @users.each_with_index do |user,i| %>
                <tr>
                  <td><%= i + 1 %></td>
                  <td><%= link_to user.email, user_path(user.id) %></td>
                  <td><%= link_to (user.full_name || user.email), user_path(user.id) %></td>
                  <td><%= user.created_at.strftime("%B %d, %Y") %></td>
                  <td><%= user.last_active.present? ? user.last_active.strftime("%B %d, %Y") : ""   %></td>
                  <% if user.active_status == "Active" %>
                    <td class="font-bold text-navy">Active</td>
                  <% else %>
                    <td class="font-bold text-danger">Deactive</td>
                  <% end %>
                  <td><%= link_to "Edit", edit_user_path(user), {class: 'btn btn-primary dim'} %></td>
                  <!-- <td><%#= link_to("Delete",user_path(user.id),{method: :delete, class: "btn btn-danger",:data => {:confirm => "Are you sure you want to Delete?"}}) %></td>
                  <td>
                    <%# if user.deactivated? %>
                      <%# link_to("Reactivate",reactivate_user_path(user.id),{method: :post,class: "btn btn-info",:data => {:confirm => "Are you sure you want to Reactivate?"}}) %>
                    <%# else %>
                      <%#= link_to("Deactivate",deactivate_user_path(user.id),{method: :post,class: "btn btn-warning",:data => {:confirm => "Are you sure you want to Deactivate?"}}) %>
                    <%# end %>
                  </td> -->
                </tr>
              <% end %>
            <% end %>
        </tbody>
      </table>
      <% if !@users.present?%>
        <div class="middle-box text-center animated fadeInDown">
          <h2>Oh Snap!!</h2>
          <h3 class="font-bold">No Record Found</h3>
          <%= link_to "Go Back", dashboard_path,{"class" => "btn btn-primary"} %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Profile</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to "Home", dashboard_path %>
      </li>
      <li>
        <%= link_to "Users", users_path %>
      </li>
      <li class="active">
        <strong>Profile</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">

</div>
</div>
<div class="wrapper wrapper-content">
  <div class="row animated fadeInRight">
    <div class="col-md-4">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Profile Detail</h5>
        </div>
        <div id="animation_box" class="animated shake">
          <div class="ibox-content no-padding border-left-right rubberBand">
            <% if @user.avatar.present? %>
              <%= image_tag @user.avatar, size: "315" %>
            <% else %>
              <img alt="image" class="img-responsive" src="<%= image_path('profile_big.jpg') %>">
            <% end %>
          </div>
        </div>
        <div class="ibox-content profile-content">
          <h4><strong>Name: </strong><%= @user.full_name || "N/A" %></h4>
          <h4><strong>Email: </strong><%= @user.email %></h4>
          <p><i class="fa fa-map-marker"></i> <%= @user.state.presence || "N/A" %></p>
          <h5>About me</h5>
          <p>
              <%= @user.description.presence || "Description Not Mentioned" %>
          </p>
          <div class="row m-t-lg">
            <div class="col-md-4">
              <span class="bar">5,3,9,6,5,9,7,3,5,2</span>
              <h5><strong><%= @user.tasks.count %></strong> Tasks</h5>
            </div>
            <div class="col-md-4">
              <span class="line">5,3,9,6,5,9,7,3,5,2</span>
              <h5><strong><%= @user.task_work_offers.count %></strong>  Offers</h5>
            </div>
            <div class="col-md-4">
              <span class="bar">5,3,2,-1,-3,-2,2,3,5,2</span>
              <h5><strong><%= @user.tasks.where(status: Task.statuses[:completed]).count %></strong> Completed</h5>
            </div>
          </div>
          <div class="user-button">
            <div class="row">
              <div class="col-md-6">
              <%= link_to("<i class = 'fa fa-minus'></i> Delete".html_safe,user_path(@user.id),{method: :delete, class: "btn btn-danger",:data => {:confirm => "Are you sure you want to Delete?"}}) %>
              </div>
              <div class="col-md-6">
              <% if @user.deactivated? %>
                <%= link_to("<i class = 'fa fa-check'></i> Reactivate".html_safe,reactivate_user_path(@user.id),{method: :post,class: "btn btn-info",:data => {:confirm => "Are you sure you want to Reactivate?"}}) %>
              <% else %>
                <%= link_to("<i class = 'fa fa-ban'></i> Deactivate".html_safe,deactivate_user_path(@user.id),{method: :post,class: "btn btn-warning",:data => {:confirm => "Are you sure you want to Deactivate?"}}) %>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>  
    </div>
    <div class="col-md-8">
        <div class="ibox float-e-margins">
          <div class="ibox-title">
            <h5>Summary</h5>
            <div class="ibox-tools">
              <a class="collapse-link">
                <i class="fa fa-chevron-up"></i>
              </a>
            </div>
          </div>
            <div class="ibox-content">
              <div>
              <button class="btn btn-primary btn-block m" style="cursor: ;"><i class="fa fa-gavel"></i> Tasks</button>
              <div class="feed-activity-list">
                <div class="feed-element">
                  <% if @user.tasks.present? %>
                    <% @user.tasks.each do |task| %>
                      <div class="feed-element">
                        <a href="#" class="pull-left">
                          <%#= image_tag task.category_image %>
                        </a>
                        <div class="media-body ">
                          <small class="pull-right text-navy"> <%= task.created_at.strftime("%B %d, %Y") %></small>
                          <strong><%= link_to(task.description.titleize, task_path(task)) %></strong> <br>
                          <!-- <small class="text-muted">Today 4:21 pm - 12.06.2014</small> -->
                          <div class="actions">
                          <% if task.is_my_offer_accepted %>
                            <a class="btn btn-xs btn-white"><i class="fa fa-thumbs-up"></i> Accepted </a>
                          <% else %>
                            <a class="btn btn-xs btn-white"><i class="fa fa-thumbs-down"></i> Not Accepted </a>
                          <% end %>
                          <a class="btn btn-xs btn-white"><i class="fa fa-angellist"></i> <%= task.status %> </a>
                          </div>
                        </div>
                      </div>  
                    <% end %>  
                  <% end %>
                </div>
                <button class="btn btn-primary btn-block m"><i class="fa fa-bullhorn"></i> Task Offered</button>
                <div class="feed-element">
                  <% if @user.task_work_offers.present? %>
                    <% @user.task_work_offers.each do |task_work_offer| %>
                      <div class="feed-element">
                        <a href="#" class="pull-left">
                          <%#= image_tag task.category_image %>
                        </a>
                        <div class="media-body ">
                          <small class="pull-right text-navy"> $ <%= task_work_offer.price %></small>
                          <strong><%= task_work_offer.task.present? ? task_work_offer.task.description.titleize : "No Description" %></strong> <br>
                          <div class="actions">
                            <% if task_work_offer.task.present? && task_work_offer.task.is_my_offer_accepted %>
                              <a class="btn btn-xs btn-white"><i class="fa fa-thumbs-up"></i> Accepted </a>
                              <a class="btn btn-xs btn-white"><i class="fa fa-angellist"></i> <%= task_work_offer.task.status %> </a>
                            <% else %>
                              <a class="btn btn-xs btn-white"><i class="fa fa-thumbs-down"></i> Not Accepted </a>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
                <!--  <h5>Portfolio</h5>
                  <div class="feed-element">
                    <a href="#" class="pull-left">
                      <img alt="image" class="img-circle" src="<%= image_path('a3.jpg') %>">
                    </a>
                    <div class="media-body ">
                      <small class="pull-right">2h ago</small>
                      <strong>Janet Rosowski</strong> add 1 photo on <strong>Monica Smith</strong>. <br>
                      <small class="text-muted">2 days ago at 8:30am</small>
                      <div class="photos">
                        <a target="_blank" href="http://24.media.tumblr.com/20a9c501846f50c1271210639987000f/tumblr_n4vje69pJm1st5lhmo1_1280.jpg"> <img alt="image" class="feed-photo" src="<%= image_path('p1.jpg') %>"></a>
                        <a target="_blank" href="http://37.media.tumblr.com/9afe602b3e624aff6681b0b51f5a062b/tumblr_n4ef69szs71st5lhmo1_1280.jpg"> <img alt="image" class="feed-photo" src="<%= image_path('p3.jpg') %>"></a>
                      </div>
                    </div>
                  </div> -->
                 
                  </div>

              </div>

            </div>
        </div>

    </div>
  </div>
</div>


<% content_for :javascript do %>
  <script type="text/javascript">

    $(function() {

        $("span.pie").peity("pie", {
            fill: ['#1ab394', '#d7d7d7', '#ffffff']
        })

        $(".line").peity("line", {
            fill: '#1ab394',
            stroke: '#169c81',
        })

        $(".bar").peity("bar", {
            fill: ["#1ab394", "#d7d7d7"]
        })


    });

  </script>
<% end %>